on:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo -n 'export var RPDK_SCHEMA = ' > src/schema.ts
          curl https://raw.githubusercontent.com/aws-cloudformation/aws-cloudformation-resource-schema/master/src/main/resources/schema/provider.definition.schema.v1.json >> src/schema.ts
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: |
            CloudFormation Resource Provider Definition MetaSchema update
          delete-branch: true
          title: CloudFormation Resource Provider Definition MetaSchema update
